openapi: 3.0.3
info:
  title: Patch Manager - Agents API
  description: API endpoints for managing patch management agents
  version: 1.0.0
  contact:
    name: Backend Team
    email: backend@patchmanager.com

servers:
  - url: http://localhost:3000/api
    description: Development server
  - url: https://api.patchmanager.com/api
    description: Production server

tags:
  - name: Agents
    description: Operations related to patch management agents

paths:
  /agents:
    get:
      tags:
        - Agents
      summary: Get all agents
      description: Retrieves a list of all registered agents with their current status
      operationId: getAgents
      responses:
        '200':
          description: Successfully retrieved list of agents
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Agent'
              examples:
                agents:
                  value:
                    - id: "1"
                      name: "MacOS 01"
                      status: "Connected"
                      lastConnectedTime: "45mins ago"
                      os: "MacOS"
                      version: "OS0.1"
                    - id: "2"
                      name: "Windows 01"
                      status: "Connected"
                      lastConnectedTime: "45mins ago"
                      os: "Win"
                      version: "WIN0.1"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /agents/downloads:
    get:
      tags:
        - Agents
      summary: Get agent download options
      description: Retrieves available agent installers for different operating systems
      operationId: getAgentDownloads
      responses:
        '200':
          description: Successfully retrieved agent download options
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AgentDownload'
              examples:
                downloads:
                  value:
                    - os: "Windows 11"
                      version: "#####"
                      releaseDate: "25/12/24"
                      downloadUrl: "/downloads/windows-agent.exe"
                    - os: "MacOS"
                      version: "#####"
                      releaseDate: "25/12/24"
                      downloadUrl: "/downloads/macos-agent.dmg"
                    - os: "Linux"
                      version: "#####"
                      releaseDate: "25/12/24"
                      downloadUrl: "/downloads/linux-agent.deb"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /agents/{id}:
    delete:
      tags:
        - Agents
      summary: Delete an agent
      description: Removes an agent from the system
      operationId: deleteAgent
      parameters:
        - name: id
          in: path
          required: true
          description: Unique identifier of the agent to delete
          schema:
            type: string
      responses:
        '200':
          description: Agent successfully deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Agent deleted successfully"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    Agent:
      type: object
      required:
        - id
        - name
        - status
        - lastConnectedTime
        - os
        - version
      properties:
        id:
          type: string
          description: Unique identifier for the agent
          example: "1"
        name:
          type: string
          description: Human-readable name for the agent
          example: "MacOS 01"
        status:
          type: string
          enum: [Connected, Disconnected]
          description: Current connection status of the agent
          example: "Connected"
        lastConnectedTime:
          type: string
          description: Human-readable timestamp of last connection
          example: "45mins ago"
        os:
          type: string
          description: Operating system of the agent
          example: "MacOS"
        version:
          type: string
          description: Version of the agent software
          example: "OS0.1"

    AgentDownload:
      type: object
      required:
        - os
        - version
        - releaseDate
        - downloadUrl
      properties:
        os:
          type: string
          enum: [Windows 11, MacOS, Linux]
          description: Operating system for the agent installer
          example: "Windows 11"
        version:
          type: string
          description: Version of the agent installer
          example: "#####"
        releaseDate:
          type: string
          description: Release date of the agent version
          example: "25/12/24"
        downloadUrl:
          type: string
          description: URL to download the agent installer
          example: "/downloads/windows-agent.exe"

    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
        code:
          type: string
          description: Error code
        details:
          type: object
          description: Additional error details

  responses:
    UnauthorizedError:
      description: Authentication is required
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error: "Unauthorized"
            code: "UNAUTHORIZED"

    NotFoundError:
      description: The requested resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error: "Resource not found"
            code: "NOT_FOUND"

    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error: "Internal server error"
            code: "INTERNAL_ERROR"

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: []
