openapi: 3.0.3
info:
  title: Patchify - Tags API
  description: API endpoints for managing asset tags with rich metadata
  version: 1.0.0
  contact:
    name: Backend Team
    email: backend@patchify.com

servers:
  - url: http://localhost:3000/v1
    description: Development server
  - url: https://api.patchify.com/v1
    description: Production server

tags:
  - name: Tags
    description: Operations for tag CRUD
  - name: Asset-Tag Relationships
    description: Many-to-many relationships between assets and tags

paths:
  /tags:
    get:
      tags:
        - Tags
      summary: Get all tags
      description: Retrieves all tags with usage statistics, sorted by usage count
      operationId: getTags
      parameters:
        - name: status
          in: query
          description: Filter by status
          schema:
            type: string
            enum: [Active, Inactive]
        - name: priority
          in: query
          description: Filter by priority
          schema:
            type: string
            enum: [Critical, High, Medium, Low]
      responses:
        '200':
          description: Successfully retrieved tags
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tag'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

    post:
      tags:
        - Tags
      summary: Create a new tag
      operationId: createTag
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTagRequest'
      responses:
        '201':
          description: Tag created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '409':
          description: Tag name already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Tag with this name already exists"

  /tags/{tagId}:
    get:
      tags:
        - Tags
      summary: Get tag by ID
      operationId: getTag
      parameters:
        - name: tagId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Tag retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
        '404':
          $ref: '#/components/responses/NotFoundError'

    put:
      tags:
        - Tags
      summary: Update tag
      operationId: updateTag
      parameters:
        - name: tagId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTagRequest'
      responses:
        '200':
          description: Tag updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
        '404':
          $ref: '#/components/responses/NotFoundError'

    delete:
      tags:
        - Tags
      summary: Delete tag
      operationId: deleteTag
      parameters:
        - name: tagId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Tag deleted successfully
        '404':
          $ref: '#/components/responses/NotFoundError'

  /assets/{assetId}/tags:
    get:
      tags:
        - Asset-Tag Relationships
      summary: Get all tags for an asset
      operationId: getAssetTags
      parameters:
        - name: assetId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Asset tags retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tag'
        '404':
          $ref: '#/components/responses/NotFoundError'

    post:
      tags:
        - Asset-Tag Relationships
      summary: Assign tags to asset
      description: Replaces existing tags with new ones (full replace, not merge)
      operationId: assignTagsToAsset
      parameters:
        - name: assetId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - tagIds
              properties:
                tagIds:
                  type: array
                  items:
                    type: string
                  description: Array of tag IDs to assign
      responses:
        '200':
          description: Tags assigned successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
        '404':
          $ref: '#/components/responses/NotFoundError'

  /assets/{assetId}/tags/{tagId}:
    delete:
      tags:
        - Asset-Tag Relationships
      summary: Remove tag from asset
      operationId: removeTagFromAsset
      parameters:
        - name: assetId
          in: path
          required: true
          schema:
            type: string
        - name: tagId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Tag removed successfully
        '404':
          $ref: '#/components/responses/NotFoundError'

  /tags/{tagId}/assets:
    get:
      tags:
        - Asset-Tag Relationships
      summary: Get all assets with a specific tag
      operationId: getTagAssets
      parameters:
        - name: tagId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Assets retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object

  /tags/bulk-assign:
    post:
      tags:
        - Asset-Tag Relationships
      summary: Bulk assign tags to multiple assets
      operationId: bulkAssignTags
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - assetIds
                - tagIds
              properties:
                assetIds:
                  type: array
                  items:
                    type: string
                  description: Asset IDs to assign tags to
                tagIds:
                  type: array
                  items:
                    type: string
                  description: Tag IDs to assign
      responses:
        '200':
          description: Tags assigned successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  assigned:
                    type: integer

  /tags/bulk-remove:
    post:
      tags:
        - Asset-Tag Relationships
      summary: Bulk remove tags from multiple assets
      operationId: bulkRemoveTags
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - assetIds
                - tagIds
              properties:
                assetIds:
                  type: array
                  items:
                    type: string
                tagIds:
                  type: array
                  items:
                    type: string
      responses:
        '200':
          description: Tags removed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  removed:
                    type: integer

  /tags/search:
    get:
      tags:
        - Tags
      summary: Search tags by name or description
      operationId: searchTags
      parameters:
        - name: q
          in: query
          required: true
          description: Search query
          schema:
            type: string
      responses:
        '200':
          description: Search results
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tag'

  /tags/popular:
    get:
      tags:
        - Tags
      summary: Get most used tags
      operationId: getPopularTags
      parameters:
        - name: limit
          in: query
          description: Maximum number of tags to return
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: Popular tags
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tag'

components:
  schemas:
    Tag:
      type: object
      required:
        - id
        - name
        - assetCount
        - createdAt
      properties:
        id:
          type: string
          example: "tag-1"
        name:
          type: string
          example: "Production"
        description:
          type: string
          example: "Production environment assets"
        color:
          type: string
          example: "red"
        icon:
          type: string
          example: "fire"
        owner:
          type: string
          example: "DevOps Team"
        manager:
          type: string
          example: "Alex Chen"
        priority:
          type: string
          enum: [Critical, High, Medium, Low]
          example: "Critical"
        status:
          type: string
          enum: [Active, Inactive]
          example: "Active"
        assetCount:
          type: integer
          example: 45
        usageCount:
          type: integer
          example: 120
        lastUsed:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        budget:
          type: string
          example: "$250,000"
        complianceRequired:
          type: boolean
          example: true
        complianceTags:
          type: array
          items:
            type: string
          example: ["SOC2", "ISO27001"]
        metadata:
          type: object
          additionalProperties: true

    CreateTagRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          maxLength: 255
        description:
          type: string
          maxLength: 500
        color:
          type: string
        icon:
          type: string
        owner:
          type: string
        manager:
          type: string
        priority:
          type: string
          enum: [Critical, High, Medium, Low]
        status:
          type: string
          enum: [Active, Inactive]
        budget:
          type: string
        complianceRequired:
          type: boolean
        complianceTags:
          type: array
          items:
            type: string
        metadata:
          type: object

    UpdateTagRequest:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        color:
          type: string
        icon:
          type: string
        owner:
          type: string
        manager:
          type: string
        priority:
          type: string
        status:
          type: string
        budget:
          type: string
        complianceRequired:
          type: boolean
        complianceTags:
          type: array
          items:
            type: string
        metadata:
          type: object

  responses:
    UnauthorizedError:
      description: Authentication required
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Authentication required"

    BadRequestError:
      description: Bad request
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string

    NotFoundError:
      description: Resource not found
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Tag not found"
